[package]
name = "play_circuit"
type = "bin"
authors = ["Zunno Team"]
compiler_version = ">=1.0.0"

[dependencies]
zk_uno = { path = "../lib" }
poseidon = { tag = "v0.2.2", git = "https://github.com/noir-lang/poseidon" }
